TYPE=VIEW
query=select `r1`.`id` AS `rom_id`,`r2`.`id` AS `sibling_rom_id`,`r1`.`platform_id` AS `platform_id`,current_timestamp() AS `created_at`,current_timestamp() AS `updated_at`,case when `r1`.`igdb_id` <=> `r2`.`igdb_id` then `r1`.`igdb_id` end AS `igdb_id`,case when `r1`.`moby_id` <=> `r2`.`moby_id` then `r1`.`moby_id` end AS `moby_id`,case when `r1`.`ss_id` <=> `r2`.`ss_id` then `r1`.`ss_id` end AS `ss_id`,case when `r1`.`launchbox_id` <=> `r2`.`launchbox_id` then `r1`.`launchbox_id` end AS `launchbox_id`,case when `r1`.`ra_id` <=> `r2`.`ra_id` then `r1`.`ra_id` end AS `ra_id`,case when `r1`.`hasheous_id` <=> `r2`.`hasheous_id` then `r1`.`hasheous_id` end AS `hasheous_id`,case when `r1`.`tgdb_id` <=> `r2`.`tgdb_id` then `r1`.`tgdb_id` end AS `tgdb_id` from (`romm`.`roms` `r1` join `romm`.`roms` `r2` on(`r1`.`platform_id` = `r2`.`platform_id` and `r1`.`id` <> `r2`.`id` and (`r1`.`igdb_id` = `r2`.`igdb_id` and `r1`.`igdb_id` is not null or `r1`.`moby_id` = `r2`.`moby_id` and `r1`.`moby_id` is not null or `r1`.`ss_id` = `r2`.`ss_id` and `r1`.`ss_id` is not null or `r1`.`launchbox_id` = `r2`.`launchbox_id` and `r1`.`launchbox_id` is not null or `r1`.`ra_id` = `r2`.`ra_id` and `r1`.`ra_id` is not null or `r1`.`hasheous_id` = `r2`.`hasheous_id` and `r1`.`hasheous_id` is not null or `r1`.`tgdb_id` = `r2`.`tgdb_id` and `r1`.`tgdb_id` is not null)))
md5=841fffcb9ebe3dbd7a19853e291bd956
updatable=1
algorithm=0
definer_user=romm
definer_host=%
suid=2
with_check_option=0
timestamp=0001760481428898345
create-version=2
source=SELECT\n                r1.id AS rom_id,\n                r2.id AS sibling_rom_id,\n                r1.platform_id AS platform_id,\n                NOW() AS created_at,\n                NOW() AS updated_at,\n                CASE WHEN r1.igdb_id <=> r2.igdb_id THEN r1.igdb_id END AS igdb_id,\n                CASE WHEN r1.moby_id <=> r2.moby_id THEN r1.moby_id END AS moby_id,\n                CASE WHEN r1.ss_id <=> r2.ss_id THEN r1.ss_id END AS ss_id,\n                CASE WHEN r1.launchbox_id <=> r2.launchbox_id THEN r1.launchbox_id END AS launchbox_id,\n                CASE WHEN r1.ra_id <=> r2.ra_id THEN r1.ra_id END AS ra_id,\n                CASE WHEN r1.hasheous_id <=> r2.hasheous_id THEN r1.hasheous_id END AS hasheous_id,\n                CASE WHEN r1.tgdb_id <=> r2.tgdb_id THEN r1.tgdb_id END AS tgdb_id\n            FROM\n                roms r1\n            JOIN\n                roms r2\n            ON\n                r1.platform_id = r2.platform_id\n                AND r1.id != r2.id\n                AND (\n                    (r1.igdb_id = r2.igdb_id AND r1.igdb_id IS NOT NULL)\n                    OR\n                    (r1.moby_id = r2.moby_id AND r1.moby_id IS NOT NULL)\n                    OR\n                    (r1.ss_id = r2.ss_id AND r1.ss_id IS NOT NULL)\n                    OR\n                    (r1.launchbox_id = r2.launchbox_id AND r1.launchbox_id IS NOT NULL)\n                    OR\n                    (r1.ra_id = r2.ra_id AND r1.ra_id IS NOT NULL)\n                    OR\n                    (r1.hasheous_id = r2.hasheous_id AND r1.hasheous_id IS NOT NULL)\n                    OR\n                    (r1.tgdb_id = r2.tgdb_id AND r1.tgdb_id IS NOT NULL)\n                )
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_uca1400_ai_ci
view_body_utf8=select `r1`.`id` AS `rom_id`,`r2`.`id` AS `sibling_rom_id`,`r1`.`platform_id` AS `platform_id`,current_timestamp() AS `created_at`,current_timestamp() AS `updated_at`,case when `r1`.`igdb_id` <=> `r2`.`igdb_id` then `r1`.`igdb_id` end AS `igdb_id`,case when `r1`.`moby_id` <=> `r2`.`moby_id` then `r1`.`moby_id` end AS `moby_id`,case when `r1`.`ss_id` <=> `r2`.`ss_id` then `r1`.`ss_id` end AS `ss_id`,case when `r1`.`launchbox_id` <=> `r2`.`launchbox_id` then `r1`.`launchbox_id` end AS `launchbox_id`,case when `r1`.`ra_id` <=> `r2`.`ra_id` then `r1`.`ra_id` end AS `ra_id`,case when `r1`.`hasheous_id` <=> `r2`.`hasheous_id` then `r1`.`hasheous_id` end AS `hasheous_id`,case when `r1`.`tgdb_id` <=> `r2`.`tgdb_id` then `r1`.`tgdb_id` end AS `tgdb_id` from (`romm`.`roms` `r1` join `romm`.`roms` `r2` on(`r1`.`platform_id` = `r2`.`platform_id` and `r1`.`id` <> `r2`.`id` and (`r1`.`igdb_id` = `r2`.`igdb_id` and `r1`.`igdb_id` is not null or `r1`.`moby_id` = `r2`.`moby_id` and `r1`.`moby_id` is not null or `r1`.`ss_id` = `r2`.`ss_id` and `r1`.`ss_id` is not null or `r1`.`launchbox_id` = `r2`.`launchbox_id` and `r1`.`launchbox_id` is not null or `r1`.`ra_id` = `r2`.`ra_id` and `r1`.`ra_id` is not null or `r1`.`hasheous_id` = `r2`.`hasheous_id` and `r1`.`hasheous_id` is not null or `r1`.`tgdb_id` = `r2`.`tgdb_id` and `r1`.`tgdb_id` is not null)))
mariadb-version=120002
